### ISSUE TITLE
Upgrade failed: err: 127 When uploading self built release.

### ISSUE THREAD

**Issue by Jaminima** [dukelec/mb#16]
When attempting to upload a release ive built myself (Windows or Linux)
I am faced with 
![image](https://user-images.githubusercontent.com/20128596/87638880-68e49f00-c73c-11ea-8b49-10d2dc5ec4d6.png)
No matter what i try doing, downgrading the MBrush using the cloner and then updating.
It seems i simply cannot upload it.

Any advice would be of great use.

**Comment by dukelec** [comment]
Please upload the tarball you created here.

**Comment by Jaminima** [comment]
[PrinCube-fw-4.31_4.16.tar.zip](https://github.com/dukelec/mb/files/4932516/PrinCube-fw-4.31_4.16.tar.zip)
Had to zip the tar as it git doesnt allow tar comments.
This one has no changes at all to it, is the latest commit.
I tried previous versions and still no luck.

**Comment by dukelec** [comment]
I tested your firmware and got the same error 127.

I logged into the printer by the UART port, kill busybox httpd, and start it again with front-end and debug enabled:
`# busybox httpd -h mb_ser -c httpd.conf -f -p 80 -vvv`

Then I upload your firmware again and get this error:
`cmd: line 57: ./mbrush-fw/run.sh: not found`

Then, I go to `mb_ser/upload/` and run `mbrush-fw/run.sh` manually:
```
# ./mbrush-fw/run.sh 
-sh: ./mbrush-fw/run.sh: not found
#
# sh mbrush-fw/run.sh 
mbrush-fw/run.sh: line 2: 
: not found
mbrush-fw/run.sh: line 7: 
: not found
mbrush-fw/run.sh: line 29: syntax error: unexpected end of file (expecting "then")
```

Finally, I found that the problem is caused by the line endings:
![Screenshot_2020-07-17_17-55-54](https://user-images.githubusercontent.com/4454365/87774414-15b33f00-c857-11ea-81a7-74bd8e6329ea.png)


Please try clone this git repo under Linux, that should solve this issue.
