### ISSUE TITLE
Hardware Problem Cyan missing upper Half - Level Shifter?

### ISSUE THREAD

**Issue by JFKBoell** [dukelec/mb#64]
Hey, i´ve got two Devices and one suddently stopped Printing Cyan correctly.
It still prints the color but just the lower half, the upper half is missing.
I tryed different Cartriges and all and nothing helped.
I switched the mainboards between the two units and the fault traveled with it so i´am certain that its some problem with the mainboard.
I already tryed contacting kongten and also the reseller but with no luck.
Any advice on where start searching?
I suspect a fault in one of the cm504b level shifters. Could that lead to Blue (cyan) just beeing printed half?
I could solder in a new one, but would be glad on any advice which one of them is in charge of driving the cyan.

**Comment by dukelec** [comment]
![Screenshot_2023-01-30_21-04-46](https://user-images.githubusercontent.com/4454365/215492780-04d778e3-ee81-4e27-91a3-99f6ce0abb96.png)

Sorry, I don't remember the pin-to-color correspondence either.

I think it should be caused by the failure of one of the 6 white MOS pins in the picture.

I suggest you do a test first, without connecting the ink cartridge, on the pogo pin of the printer, one of the 6 pins of the MOS is connected in series through an external 10k resistor to any GND pin. Then, in the power-on state, press and hold the print button to enter the cleaning mode, and observe which MOS pin has no output (the corresponding LED light is not on).

![smt_top](https://user-images.githubusercontent.com/4454365/215494549-f0fac940-1367-4885-a9d6-62204ff8b639.png)

![smt_bottom](https://user-images.githubusercontent.com/4454365/215494559-38f58ad4-6f77-4e4c-b6b4-628f8b096e3b.png)

Other than a bad contact, it is likely that the corresponding 3.9 Ohm resistors are blown, which I have pointed out with arrows, and you can also measure these directly. Meanwhile, one of them is connected like this in the schematic:

![Screenshot_2023-01-30_21-38-36](https://user-images.githubusercontent.com/4454365/215495261-93e9ea6b-26bc-40c9-adf7-76b88c32712c.png)

**Comment by JFKBoell** [comment]
Hey, incredible!
Thank you soooo much for your help. I really appreciate it!
Found out that Resistor R50 really was shot. It meassured 20k instead of 4 ;-)
 I just had 1206 Footprint laying around in 4 Ohms which was way tooo big, but i managed to Unsolder four times 1 Ohm from electronic thrash laying around. I then connected it with coated copper wire and secured it with uv resin.
 It doesnt look beautiful, but: it fixed it!

See captures with cheap-o-scope:

![WIN_20230130_20_52_33_Pro](https://user-images.githubusercontent.com/27411921/215598112-bfc11ea9-20cf-447d-b572-36470744cfc1.jpg)
![WIN_20230130_21_56_14_Pro](https://user-images.githubusercontent.com/27411921/215598114-0d592b77-276f-457d-b999-575df2828e62.jpg)
![WIN_20230130_21_56_36_Pro](https://user-images.githubusercontent.com/27411921/215598117-b9c35cd0-40bf-4af1-b073-18a4c59ca5aa.jpg)

An now another issue:
The unit with the working mainboard had the problem of switching itself off randomly in mid print.
Mostly when it was heavy used for long and fast prints. If i would use it very slow then it almost never occured.
The device with the broken cyan never did that so i suppose there is also something wrong.
I found that the bottom casing of the device contained a smeary substance.
But the Battery looks good and flat and clean and also is dry.
But on the lower pcb there was also some smear and i suspect, that the part marked in this picture is a capacitor?
Or is it something else? Could it be leaking and lead to the described behaviour?

![20230130_204017](https://user-images.githubusercontent.com/27411921/215600413-a6ee0325-e29a-4357-bb8a-83a844b25ede.jpg)

Again many thanks and i think that the mbrush is awsome thing :-)

**Comment by dukelec** [comment]
> the problem of switching itself off randomly in mid print

When the battery is low, and the print content is dark, and the print speed is fast, we may encountered in this problem.  
Try fully charge the battery first.

> The device with the broken cyan never did that

Without drive the half of cyan nozzles, the battery current during printing is much lower, the voltage may not drop to the limit.


The part marked in this picture is not capacitor, it's a buzzer.

**Comment by JFKBoell** [comment]
Alright, the additional hint concerning the resistor sounds really good, i will get one 0402 and put it in.
I think it was my fault when i broke it, because i was printing on a kind of ruff metal surface (Metal Door), i think one metal spike somehow hit in the printhead and issued a short. That was two years ago, and ever since then i was a bit sad that my printcube broke. Now i remembered that i wanted to repair it, which was now successfully accomplished.
Thank you very much again and I will observe if and when the switching off issue occurs in the future.
